### ISSUE TITLE
没有起作用

### ISSUE THREAD

**Issue by llds66** [Dave-12138/miyoushe-emoticon-in-discussion#3]
安装成功后，没有起作用

**Comment by Dave-12138** [comment]
手机还是电脑啊？啥浏览器啊？啥脚本加载器啊？真装上了吗？是不是它还在获取米游社表情包还没生成界面呢？

**Comment by llds66** [comment]
@Dave-12138  抱歉，我没仔细看文档，原来是在discussions界面里使用，(我是在issues 界面查看的)，但是在discussions界面，初次进入没有，手动刷新可以成功出现。

信息：
- Windows 11
- Chrome 版本 128.0.6613.120（正式版本） （64 位）
![image](https://github.com/user-attachments/assets/8f1b32e9-9cc3-4966-86af-bc3d962986e9)

**Comment by llds66** [comment]
疑问：为什么不支持在issues里使用呢？

**Comment by Dave-12138** [comment]
> 疑问：为什么不支持在issues里使用呢？

一会儿加
